apiVersion: v1
kind: Service
metadata:
  name: mydjango
  namespace: myapp
  labels:
    app: mydjango
spec:
  ports:
    - port: 8000
      protocol: TCP
  selector:
    app: mydjango
    tier: frontend
  # clusterIP: 10.0.171.239
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mydjango
  namespace: myapp
  labels:
    app: mydjango
spec:
  selector:
    matchLabels:
      app: mydjango
      tier: frontend
  template:
    metadata:
      labels:
        app: mydjango
        tier: frontend
    spec:
      containers:
      - name: mydjango
        image: mydjango:0.0.1
        ports:
        - containerPort: 8000
        env:
        - name: MY_VARIABLE
          valueFrom:
            configMapKeyRef:
              name: mydjango-configmap
              key: MYTEST
        volumeMounts:
        - name: mydjango-configmap-volume
          mountPath: /app/mysite/mysettings.py
          subPath: mysettings.py
        ports:
        - containerPort: 8000
          name: mydjango
      volumes:
      - name: mydjango-configmap-volume
        configMap:
          name: mydjango-configmap

