apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: myapp
  labels:
    app: mydjango
spec:
  ports:
    - port: 3306
  selector:
    app: mydjango
    tier: database
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  namespace: myapp
  labels:
    app: mydjango
spec:
  selector:
    matchLabels:
      app: mydjango
      tier: database
  template:
    metadata:
      labels:
        app: mydjango
        tier: database
    spec:
      containers:
      - image: mysql:5
        name: mysql
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql-svc