apiVersion: v1
kind: Service
metadata:
  name: mydjango
  labels:
    app: mydjango
spec:
  ports:
    - port: 8000
  selector:
    app: mydjango
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mydjango
  labels:
    app: mydjango
spec:
  selector:
    matchLabels:
      app: mydjango
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mydjango
        tier: frontend
    spec:
      initContainers:
      - name: init-mydjango
        image: busybox
        command: ['sh', '-c', 'until nslookup mysql; do echo waiting for mysql; sleep 2; done;']
      containers:
      - name: mydjango
        image: mydjango:0.0.1
        ports:
        - containerPort: 8000
          name: mydjango
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10